# Houdini Type Extensions

GEO_EXTENSIONS = ['.abc', 
				  '.ai',
				  '.ass',
				  '.bgeo','.bgeo.sc','.bgeo.bz2','.bgeo.gz','.bgeo.lzma','.bgeo.sc',
				  '.bhclassic','.bhclassic.bz2','.bhclassic.lzma','.bhclassic.gz','.bhclassic.sc','.bhclassicgz','.bhclassicsc',
				  '.bjson','.bjson.gz','.bjson.sc','.bjsongz','.bjsonsc',
				  '.bpoly',
				  '.bstl',
				  '.d',
				  '.dxf',
				  '.eps',
				  '.fbx',
				  '.geo','.geo.bz2','.geo.gz','.geo.lzma','.geo.sc','.geogz','.geosc',
				  '.hclassic','.hclassic.bz2','.hclassic.gz','.hclassic.lzma','.hclassic.sc','.hclassicgz','.hclassicsc',
				  '.iges',
				  '.igs',
				  '.json','.json.gz','.json.sc','.jsongz','.jsonsc',
				  '.lw',
				  '.lwp',
				  '.obj',
				  '.pc',
				  '.pdb',
				  '.ply',
				  '.pmap',
				  '.poly',
				  '.rib',
				  '.stl',
				  '.vdb']


IMAGE_EXTENSIONS = ['.als',
					'.bmp',
					'.cin',
					'.dsm',
					'.exr',
					'.hdr',
					'.ies',
					'.jpeg',
					'.jpg',
					'.kdk',
					'.pic',
					'.pic.gz', 'pic.Z', 'picgz', '.piclc', 'picnc', 'picZ',
					'.pix',
					'.png',
					'.psb',
					'.psd',
					'.ptex',
					'.ptx',
					'.qtl',
					'.rat',
					'.rgb', 'rgba',
					'.rla', '.rla16',
					'.rlb', 'rlb16',
					'.sgi',
					'.si',
					'.tbf',
					'.tga',
					'.tif', 'tif16', 'tif3', 'tif32', 'tiff',
					'.vst',
					'.vtg',
					'.yuv']


CHAN_EXTENSIONS = ['.aif',
				   '.aifc',
				   '.aiff',
				   '.bchan',
				   '.bclip',
				   '.bclipnc',
				   '.chan',
				   '.chn',
				   '.clip',
				   '.mp2',
				   '.mp3',
				   '.wav']


ASSET_EXTENSIONS = ['.hda','hdalc','hdanc',
		            '.otl','.otllc','otlnc']